name: Marvels On Board
favicon: null
layout_spectrum: 0.7312939662951976
typography_spectrum: 0.3890633308328688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8329984755255282
  lightness: 0.9627799047157168
  saturation: 0.946198602905497
  rhythmicContrast: 0.2059765518642962
purpose: []
